# Generated by Django 4.2.11 on 2025-02-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('args', models.CharField(max_length=200)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('is_triggered', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
